/* Database schema to keep the structure of entire database. */

--  project0

create table animals(
    id int generated by default as identity (start with 1 increment by 1),
    name text not null,
    date_of_birth date not null,
    escape_attempts int not null,
    neutered bool not null,
    weight_kg decimal not null,
    primary key (id)
);

-- project1

alter table animals
add column species text;

begin;
savepoint sp0;
update animals
set species = 'unspecified';
select * from animals;
rollback to sp0;

begin;
update animals
set species = 'digimon'
where name like '%mon';
update animals
set species = 'pokemon'
where species is null;
commit;
select * from animals;

begin;
delete from animals;
rollback;
select * from animals;

begin;
delete from animals
where date_of_birth > '2022-01-01';
savepoint sp0;
update animals
set weight_kg = weight_kg * (-1);
rollback to sp0;
update animals
set weight_kg = weight_kg * (-1)
where weight_kg < 0;
commit;
select * from animals;