create table patients(
    id int generated by default as identity (start with 1 increment by 1),
    name text not null,
    date_of_birth date not null,
    primary key (id)
);

create table medical_histories(
    id int generated by default as identity (start with 1 increment by 1),    
    admitted_at timestamp not null,
    patient_id int not null,
    status varchar not null,
    primary key (id)
);

create table treatments(
    id int generated by default as identity (start with 1 increment by 1),
    type varchar not null,
    name varchar not null,
    primary key (id)
);

create table invoices(
    id int generated by default as identity (start with 1 increment by 1),
    total_amount int not null,
    generated_at timestamp not null,
    payed_at timestamp not null,
    medical_history_id int not null,
    primary key (id)
);

create table invoice_items(
    id int generated by default as identity (start with 1 increment by 1),
    unit_price decimal not null,
    quantity int not null,
    total_price decimal not null,
    invoice_id int not null,
    treatment_id int not null,
    primary key (id),
    foreign key (treatment_id) references treatments(id),
    foreign key (invoice_id) references invoices(id)
);