-- drop table animals;
-- create table animals(
--     id int generated by default as identity (start with 1 increment by 1),
--     name text not null,
--     date_of_birth date not null,
--     escape_attempts int not null,
--     neutered bool not null,
--     weight_kg decimal not null,
--     primary key (id)
-- );
-- insert into 
--     animals (name, date_of_birth, escape_attempts, neutered, weight_kg)
-- VALUES
--     ('Agumon', '2020-02-03', 0, true, 10.23),
--     ('Gabumon', '2018-11-15', 2, true, 8.00),
--     ('Pikachu', '2021-01-07', 1, false, 15.04),
--     ('Devimon', '2017-05-12', 5, true, 11.00);

-- select * from animals;

-- select * from animals where name like '%mon';

-- select name from animals where 
--     date_of_birth >= '2016-01-01'
--     and date_of_birth < '2019-12-31';

-- select name from animals where
--     neutered = true
--     and escape_attempts < 3;

-- select date_of_birth from animals where
--     name in ('Agumon', 'Pikachu');

-- select name, escape_attempts from animals where
--     weight_kg > 10.5;

-- select * from animals where
--     neutered = true;

-- select * from animals where
--     name != 'Gabumon';

-- select * from animals where
--     weight_kg >= 10.4
--     and weight_kg <= 17.3;